### ISSUE TITLE
Problem to compile in raspberry pi 2

### ISSUE THREAD

**Issue by cpcbegin** [tuero/rocksndiamonds#27]
In file included from /home/pi/opt/retromultiinstaller/opt/rocksndiamonds/src/ai/ai_entry.cpp:22:
/home/pi/opt/retromultiinstaller/opt/rocksndiamonds/src/ai/include/logger.h:18:10: fatal error: plog/Log.h: No existe el fichero o el directorio
 #include <plog/Log.h>
          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/rocksndiamonds_headless.dir/build.make:1012: CMakeFiles/rocksndiamonds_headless.dir/src/ai/ai_entry.cpp.o] Error 1
make[2]: *** Se espera a que terminen otras tareas....
In file included from /home/pi/opt/retromultiinstaller/opt/rocksndiamonds/src/ai/controller/controller.cpp:19:
/home/pi/opt/retromultiinstaller/opt/rocksndiamonds/src/ai/include/logger.h:18:10: fatal error: plog/Log.h: No existe el fichero o el directorio

**Comment by tuero** [comment]
I'm guessing you didn't do a recursive clone to get all the submodules, as plog is one of them. Maybe try that.

**Comment by cpcbegin** [comment]
It works, thanks!
You can close this issue.
